### ISSUE TITLE
can't complie in kernel3.4

### ISSUE THREAD

**Issue by xiezhanyan** [NEKTech-Labs/wrapfs-nektech#27]
Is there a solution about this, thanks

**Comment by pankaj1jul** [comment]
We have fixed this. Just merging the changes. Please use the latest one.

**Comment by pankaj1jul** [comment]
I will ask Developers to make it available for all the possible Kernel Version with the support matrix. Thanks for reaching out to us.

**Comment by xiezhanyan** [comment]
still can't complie, kernel3.4.39 
fs/wrapfs/file.c: In function ‘wrapfs_read’:
fs/wrapfs/file.c:29:6: error: implicit declaration of function ‘file_inode’ [-Werror=implicit-function-declaration]
fs/wrapfs/file.c:29:6: warning: passing argument 2 of ‘fsstack_copy_attr_atime’ makes pointer from integer without a cast [enabled by default]
include/linux/fs_stack.h:15:20: note: expected ‘const struct inode *’ but argument is of type ‘int’
fs/wrapfs/file.c: In function ‘wrapfs_write’:
fs/wrapfs/file.c:50:6: warning: passing argument 2 of ‘fsstack_copy_inode_size’ makes pointer from integer without a cast [enabled by default]
include/linux/fs_stack.h:12:13: note: expected ‘struct inode *’ but argument is of type ‘int’
fs/wrapfs/file.c:52:6: warning: passing argument 2 of ‘fsstack_copy_attr_times’ makes pointer from integer without a cast [enabled by default]
include/linux/fs_stack.h:21:20: note: expected ‘const struct inode *’ but argument is of type ‘int’
fs/wrapfs/file.c: At top level:
fs/wrapfs/file.c:58:53: warning: ‘struct dir_context’ declared inside parameter list [enabled by default]
fs/wrapfs/file.c:58:53: warning: its scope is only this definition or declaration, which is probably not what you want [enabled by default]
fs/wrapfs/file.c: In function ‘wrapfs_readdir’:
fs/wrapfs/file.c:65:2: error: implicit declaration of function ‘iterate_dir’ [-Werror=implicit-function-declaration]
fs/wrapfs/file.c:69:6: warning: passing argument 2 of ‘fsstack_copy_attr_atime’ makes pointer from integer without a cast [enabled by default]
include/linux/fs_stack.h:15:20: note: expected ‘const struct inode *’ but argument is of type ‘int’
fs/wrapfs/file.c: In function ‘wrapfs_unlocked_ioctl’:
fs/wrapfs/file.c:90:11: warning: passing argument 1 of ‘fsstack_copy_attr_all’ makes pointer from integer without a cast [enabled by default]
include/linux/fs_stack.h:11:13: note: expected ‘struct inode *’ but argument is of type ‘int’
fs/wrapfs/file.c:90:11: warning: passing argument 2 of ‘fsstack_copy_attr_all’ makes pointer from integer without a cast [enabled by default]
include/linux/fs_stack.h:11:13: note: expected ‘const struct inode *’ but argument is of type ‘int’
fs/wrapfs/file.c: In function ‘wrapfs_open’:
fs/wrapfs/file.c:193:2: warning: passing argument 1 of ‘dentry_open’ from incompatible pointer type [enabled by default]
include/linux/fs.h:2024:22: note: expected ‘struct dentry *’ but argument is of type ‘struct path *’
fs/wrapfs/file.c:193:2: warning: passing argument 2 of ‘dentry_open’ makes pointer from integer without a cast [enabled by default]
include/linux/fs.h:2024:22: note: expected ‘struct vfsmount *’ but argument is of type ‘unsigned int’
fs/wrapfs/file.c:193:2: warning: passing argument 3 of ‘dentry_open’ makes integer from pointer without a cast [enabled by default]
include/linux/fs.h:2024:22: note: expected ‘int’ but argument is of type ‘const struct cred *’
fs/wrapfs/file.c:193:2: error: too few arguments to function ‘dentry_open’
include/linux/fs.h:2024:22: note: declared here
fs/wrapfs/file.c: In function ‘wrapfs_fsync’:
fs/wrapfs/file.c:251:2: error: implicit declaration of function ‘__generic_file_fsync’ [-Werror=implicit-function-declaration]
fs/wrapfs/file.c: At top level:
fs/wrapfs/file.c:294:2: error: unknown field ‘iterate’ specified in initializer
fs/wrapfs/file.c:294:2: warning: initialization from incompatible pointer type [enabled by default]
fs/wrapfs/file.c:294:2: warning: (near initialization for ‘wrapfs_dir_fops.write’) [enabled by default]
fs/wrapfs/inode.c: In function ‘wrapfs_create’:
fs/wrapfs/inode.c:28:5: error: incompatible type for argument 4 of ‘vfs_create’
include/linux/fs.h:1545:12: note: expected ‘struct nameidata *’ but argument is of type ‘bool’
cc1: some warnings being treated as errors

fs/wrapfs/inode.c: In function ‘wrapfs_link’:
fs/wrapfs/inode.c:64:10: error: too many arguments to function ‘vfs_link’
include/linux/fs.h:1549:12: note: declared here
fs/wrapfs/inode.c: In function ‘wrapfs_unlink’:
fs/wrapfs/inode.c:96:2: error: too many arguments to function ‘vfs_unlink’
include/linux/fs.h:1551:12: note: declared here
make[2]: *** [fs/wrapfs/file.o] 错误 1
make[2]: fs/wrapfs/inode.c: In function ‘wrapfs_rename’:
fs/wrapfs/inode.c:288:5: error: too many arguments to function ‘vfs_rename’
include/linux/fs.h:1552:12: note: declared here
*** 正在等待未完成的任务....fs/wrapfs/inode.c: At top level:
fs/wrapfs/inode.c:338:27: warning: extra tokens at end of #ifdef directive [enabled by default]
fs/wrapfs/inode.c: In function ‘wrapfs_setattr’:
fs/wrapfs/inode.c:438:8: error: too many arguments to function ‘notify_change’
include/linux/fs.h:2214:12: note: declared here
fs/wrapfs/inode.c: In function ‘wrapfs_getattr’:
fs/wrapfs/inode.c:465:2: warning: passing argument 1 of ‘vfs_getattr’ from incompatible pointer type [enabled by default]
include/linux/fs.h:2473:12: note: expected ‘struct vfsmount *’ but argument is of type ‘struct path *’
fs/wrapfs/inode.c:465:2: warning: passing argument 2 of ‘vfs_getattr’ from incompatible pointer type [enabled by default]
include/linux/fs.h:2473:12: note: expected ‘struct dentry *’ but argument is of type ‘struct kstat *’
fs/wrapfs/inode.c:465:2: error: too few arguments to function ‘vfs_getattr’
include/linux/fs.h:2473:12: note: declared here
fs/wrapfs/inode.c: At top level:
fs/wrapfs/inode.c:480:27: warning: extra tokens at end of #ifdef directive [enabled by default]
fs/wrapfs/inode.c:485:14: error: ‘kfree_put_link’ undeclared here (not in a function)
fs/wrapfs/inode.c:489:2: warning: initialization from incompatible pointer type [enabled by default]
fs/wrapfs/inode.c:489:2: warning: (near initialization for ‘wrapfs_dir_iops.create’) [enabled by default]
fs/wrapfs/inode.c:490:2: warning: initialization from incompatible pointer type [enabled by default]
fs/wrapfs/inode.c:490:2: warning: (near initialization for ‘wrapfs_dir_iops.lookup’) [enabled by default]

**Comment by xiezhanyan** [comment]
by the way, android(aosp) use fuse fs for sdcard partition. wrapfs vs fusefs, it improve io speed.
i think you guys can merge wrapfs into aosp, it will help a lot.
